import { test, expect } from '@playwright/test'

// Helper: build a simple cantilever with one point load and run analysis
async function setupAndRunAnalysis(page: Parameters<typeof test>[1] extends (...args: infer A) => unknown ? A[1] : never) {
  await page.goto('/workspace')
  await page.locator('#structure-canvas canvas').waitFor({ state: 'attached', timeout: 8000 })

  const canvasBox = await page.locator('#structure-canvas').boundingBox()
  const cx = canvasBox!.x + canvasBox!.width / 2
  const cy = canvasBox!.y + canvasBox!.height / 2

  // Add two nodes: left (N1) and right (N2) of center
  await page.keyboard.press('n')
  await page.mouse.click(cx - 80, cy)
  await page.waitForTimeout(80)
  await page.mouse.click(cx + 80, cy)
  await page.waitForTimeout(80)

  // Add member: click N1 position, then N2 position
  await page.keyboard.press('m')
  await page.mouse.click(cx - 80, cy)
  await page.waitForTimeout(50)
  await page.mouse.click(cx + 80, cy)
  await page.waitForTimeout(80)

  // Fix N1: SELECT mode, click N1 position
  await page.keyboard.press('s')
  await page.mouse.click(cx - 80, cy)
  await page.waitForTimeout(100)
  const supportSelect = page.locator('select').filter({ hasText: 'Pinned' }).first()
  if (await supportSelect.isVisible({ timeout: 1000 }).catch(() => false)) {
    await supportSelect.selectOption('fixed')
    await page.waitForTimeout(50)
  }

  // Add point load on N2: press L, click N2 position
  await page.keyboard.press('l')
  await page.mouse.click(cx + 80, cy)
  await page.waitForTimeout(150)
  const addBtn = page.locator('button:has-text("Add Load")').first()
  if (await addBtn.isVisible({ timeout: 1000 }).catch(() => false)) {
    await addBtn.click()
    await page.waitForTimeout(100)
  }

  // Run analysis
  await page.getByRole('button', { name: '▶ Run' }).click()
  await page.waitForTimeout(800)
}

test.describe('Report view — static sections (no analysis)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/report')
  })

  test('report page is scrollable', async ({ page }) => {
    // Page should have a scrollable container (not overflow-hidden)
    const root = page.locator('.overflow-y-auto').first()
    await expect(root).toBeVisible()
  })

  test('header: title, date, code reference, software', async ({ page }) => {
    await expect(page.getByText('Structural Analysis Report')).toBeVisible()
    await expect(page.getByText(/Code: AISC 360/)).toBeVisible()
    await expect(page.getByText('Software: StructCalc')).toBeVisible()
  })

  test('header: units line uses settings unit display', async ({ page }) => {
    await expect(page.getByText(/Units: kN, m, MPa/)).toBeVisible()
  })

  test('section 8: structure diagram placeholder shown when no snapshot', async ({ page }) => {
    await expect(page.getByText('8. Structure Diagram')).toBeVisible()
    await expect(page.getByText(/Run analysis on the Workspace/)).toBeVisible()
  })

  test('section 2: model summary', async ({ page }) => {
    await expect(page.getByText('2. Model Summary')).toBeVisible()
  })

  test('section 1: design criteria shows AISC 360 and φ values', async ({ page }) => {
    await expect(page.getByText('1. Design Criteria')).toBeVisible()
    await expect(page.getByText('AISC 360-10 (LRFD)')).toBeVisible()
    await expect(page.getByText('TIS 1228 (Thai Industrial Standard)')).toBeVisible()
  })

  test('section 1: PASS/MARGINAL/FAIL thresholds come from settings (default 0.8 / 1)', async ({ page }) => {
    // default urMarginal=0.8, urFail=1.0 — rendered in the table
    await expect(page.getByText(/UR < 0.8/)).toBeVisible()
    await expect(page.getByText(/UR ≥ 1/)).toBeVisible()
  })

  test('section 3: nodes', async ({ page }) => {
    await expect(page.getByText('3. Nodes')).toBeVisible()
  })

  test('section 4: members', async ({ page }) => {
    await expect(page.getByText('4. Members')).toBeVisible()
  })

  test('section 6: load combinations', async ({ page }) => {
    await expect(page.getByText('6. Load Combinations')).toBeVisible()
  })

  test('section 7: applied loads', async ({ page }) => {
    await expect(page.getByText('7. Applied Loads')).toBeVisible()
  })

  test('print button is visible', async ({ page }) => {
    await expect(page.getByRole('button', { name: 'Print / Save PDF' })).toBeVisible()
  })

  test('footer contains StructCalc branding', async ({ page }) => {
    await expect(page.getByText(/Generated by StructCalc/)).toBeVisible()
  })
})

test.describe('Report view — post-analysis sections', () => {
  test.beforeEach(async ({ page }) => {
    await setupAndRunAnalysis(page)
    // Navigate via SPA link to preserve Pinia state (solver results are in-memory only)
    await page.getByRole('link', { name: 'Report' }).click()
    await page.waitForTimeout(500)
  })

  test('section 8: structure diagram shows image after analysis', async ({ page }) => {
    await expect(page.getByText('8. Structure Diagram')).toBeVisible()
    const img = page.locator('img[alt="Structure diagram"]')
    await expect(img).toBeVisible()
    const src = await img.getAttribute('src')
    // Three.js WebGL canvas produces PNG snapshots
    expect(src).toMatch(/^data:image\/(png|svg\+xml);base64,/)
  })

  test('section 2: summary shows design result pass count', async ({ page }) => {
    await expect(page.getByText(/members PASS/)).toBeVisible()
  })

  test('section 5: steel profile parameters hidden when no profile assigned', async ({ page }) => {
    // No profile assigned in this simple test — section should be absent
    await expect(page.getByText('5. Steel Profile Parameters')).not.toBeVisible()
  })

  test('section 9: support reactions visible', async ({ page }) => {
    await expect(page.getByText('9. Support Reactions')).toBeVisible()
  })

  test('section 10: nodal displacements visible with unit column header', async ({ page }) => {
    await expect(page.getByText('10. Nodal Displacements')).toBeVisible()
    // Column header uses selected unit (default: m)
    await expect(page.getByText(/ux \(m\)/)).toBeVisible()
  })

  test('section 11: member end forces uses member label not raw ID', async ({ page }) => {
    await expect(page.getByText('11. Member End Forces')).toBeVisible()
    // Member label M1 should appear in the table, not a raw UUID slice
    await expect(page.locator('section').filter({ hasText: '11. Member End Forces' })
      .locator('td').filter({ hasText: 'M1' })).toBeVisible()
  })

  test('section 12: design assessment (LRFD) visible with UR columns', async ({ page }) => {
    await expect(page.getByText('12. Design Assessment')).toBeVisible()
    await expect(page.getByText(/UR.*axial|URaxial/i).first()).toBeVisible()
    await expect(page.getByText(/members pass/i).last()).toBeVisible()
  })
})
